# Generated by Django 3.2.9 on 2022-02-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0004_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbio',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
