# Generated by Django 3.2.9 on 2022-02-13 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.CharField(choices=[('All', 'All'), ('Friends', 'Friends')], default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
