# Generated by Django 3.2.9 on 2022-02-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0009_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
